// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_B0hGx7v-GS4GlZr4stW5p5RtC0XlabU',
    appId: '1:503697910818:web:1f8d4e263f8faf42fe2e7b',
    messagingSenderId: '503697910818',
    projectId: 'chat-6ef4d',
    authDomain: 'chat-6ef4d.firebaseapp.com',
    storageBucket: 'chat-6ef4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHsmS38vbf8H_u8ktZPBmCBbx3v3F0t4',
    appId: '1:503697910818:android:86105eb2b726cbf4fe2e7b',
    messagingSenderId: '503697910818',
    projectId: 'chat-6ef4d',
    storageBucket: 'chat-6ef4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsmfpnz-lfC_GwBnIFLkp9VNN255kYrfs',
    appId: '1:503697910818:ios:9185660949fd7c63fe2e7b',
    messagingSenderId: '503697910818',
    projectId: 'chat-6ef4d',
    storageBucket: 'chat-6ef4d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsmfpnz-lfC_GwBnIFLkp9VNN255kYrfs',
    appId: '1:503697910818:ios:9185660949fd7c63fe2e7b',
    messagingSenderId: '503697910818',
    projectId: 'chat-6ef4d',
    storageBucket: 'chat-6ef4d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_B0hGx7v-GS4GlZr4stW5p5RtC0XlabU',
    appId: '1:503697910818:web:1e364ece6a469fa1fe2e7b',
    messagingSenderId: '503697910818',
    projectId: 'chat-6ef4d',
    authDomain: 'chat-6ef4d.firebaseapp.com',
    storageBucket: 'chat-6ef4d.appspot.com',
  );
}
